"""social login

Revision ID: 34ef6009d5aa
Revises: a9f72b2fd3bd
Create Date: 2025-05-07 21:29:26.216847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34ef6009d5aa'
down_revision: Union[str, None] = 'a9f72b2fd3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_provider', sa.Enum('LOCAL', 'GOOGLE', name='authprovider', native_enum=False, length=30), server_default='LOCAL', nullable=False))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'auth_provider')
    # ### end Alembic commands ###
