"""Add is_deleted to image models

Revision ID: f8c352f0b5d4
Revises: 9bb2fcd7cd1d
Create Date: 2025-04-30 19:52:20.949994

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f8c352f0b5d4'
down_revision: Union[str, None] = '9bb2fcd7cd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawingimage', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('postimage', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postimage', 'is_deleted')
    op.drop_column('drawingimage', 'is_deleted')
    # ### end Alembic commands ###
