"""Rename to nickname

Revision ID: 1fe758972e27
Revises: a711b0641508
Create Date: 2025-04-29 19:45:59.124650

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1fe758972e27'
down_revision: Union[str, None] = 'a711b0641508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
