"""Add created_at and updated_at to image models

Revision ID: 9bb2fcd7cd1d
Revises: b135852a2d7c
Create Date: 2025-04-30 19:35:01.498643

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9bb2fcd7cd1d'
down_revision: Union[str, None] = 'b135852a2d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawingimage', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('drawingimage', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('postimage', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('postimage', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postimage', 'updated_at')
    op.drop_column('postimage', 'created_at')
    op.drop_column('drawingimage', 'updated_at')
    op.drop_column('drawingimage', 'created_at')
    # ### end Alembic commands ###
