"""relationships

Revision ID: 8abc57271e1d
Revises: 17f7f65d3811
Create Date: 2025-05-02 15:00:11.428322

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8abc57271e1d'
down_revision: Union[str, None] = '17f7f65d3811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'drawing', ['drawing_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'drawing', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'drawing', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'image', 'drawing', ['drawing_id'], ['id'])
    op.create_foreign_key(None, 'image', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'drawing', type_='foreignkey')
    op.drop_constraint(None, 'drawing', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
