"""Add is_deleted to Drawing

Revision ID: af46352b5d82
Revises: f8c352f0b5d4
Create Date: 2025-04-30 20:18:58.181337

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af46352b5d82'
down_revision: Union[str, None] = 'f8c352f0b5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawing', 'is_deleted')
    # ### end Alembic commands ###
