[project]
name = "geugeu"
version = "0.1.0"
description = "GeuGeu web application server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "pydantic-settings>=2.8.1",
    "uvicorn[standard]>=0.34.0",
]
